### ISSUE TITLE
Incorrect output when using `read_namespaced_pod_log`

### ISSUE THREAD

**Issue by poul1x** [tomplus/kubernetes_asyncio#152]
I see incorrect output when using `read_namespaced_pod_log`.

Example yaml:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: echo
spec:
  restartPolicy: Never
  containers:
    - name: echo
      image: busybox
      command: ['echo', '{"a": "b"}']
```

`kubectl` (expected) output:

```bash
kubectl logs echo
# {"a": "b"}
```

code:

```python
    async def get_pod_logs(self, name):
        kw = {
            "limit_bytes": limit_bytes,
        }

        api_v1 = CoreV1Api(self._client)
        return await api_v1.read_namespaced_pod_log(name, self._namespace, **kw)
```

`read_namespaced_pod_log` output:
```
"{'a': 'b'}"
```

When I echo from pod something like this: `'==={"a": "b"}'`, that behaviour is not triggered.

**OS**: linux debian 10
**Python version**: 3.7
**kubernetes-asyncio version**: 12.1.0
