### ISSUE TITLE
Malformed JSON response, the 'object' and/or 'type' field is missing in JSON

### ISSUE THREAD

**Issue by Qubad786** [tomplus/kubernetes_asyncio#170]
Steps to reproduce
----
1. Create a pod which is stuck in initialization e.g.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox-79d6c664ff-zsr9f
spec:
  initContainers:
  - name: bb
    command:
    - sh
    - -c
    - tail -f /dev/null
    image: busybox
    imagePullPolicy: Always
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zxjnv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
```

2. Make sure its in `PodInitializing`:
```bash
$ kubectl get po
busybox-79d6c664ff-zsr9f   0/1     Init:0/1           0          27m

$ kubectl logs po/busybox-79d6c664ff-zsr9f -c busybox
Error from server (BadRequest): container "busybox" in pod "busybox-79d6c664ff-zsr9f" is waiting to start: PodInitializing
```

3. k8s client snippet that results in a bare exception:
```python
import asyncio
from kubernetes_asyncio import client, config
from kubernetes_asyncio.watch import Watch
from kubernetes_asyncio.client.api_client import ApiClient


async def main():
    await config.load_kube_config()
    api = ApiClient()
    watch = Watch()
    async with watch.stream(
        client.CoreV1Api(api).read_namespaced_pod_log,
        name="busybox-79d6c664ff-zsr9f",
        container="busybox",
        namespace="default"
    ) as stream:
        # v1 = client.CoreV1Api(api)
        print([
            e async for e in stream
        ])

if __name__ == '__main__':
    asyncio.run(main())

---    
Exception: Malformed JSON response, the 'object' and/or 'type' field is missing. JSON: {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'container "busybox" in pod "busybox-79d6c664ff-zsr9f" is waiting to start: PodInitializing', 'reason': 'BadRequest', 'code': 400}
```

Actual behavior:
-----
```python
Exception: Malformed JSON response, the 'object' and/or 'type' field is missing. JSON: {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'container "busybox" in pod "busybox-79d6c664ff-zsr9f" is waiting to start: PodInitializing', 'reason': 'BadRequest', 'code': 400}
```

Expected behavior:
-----
A meaningful exception scheme that can be handled by calling body to extract information and present to the end user

Thanks!
